name: Deploy

on:
  push:
    branches:
      - main

# 添加必要的权限配置
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 # 更新到 v4

      - name: Setup Node
        uses: actions/setup-node@v4 # 更新到 v4
        with:
          node-version: '20' # 建议指定 Node 版本

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4 # 更新到 v4 版本
        with:
          name: production-files
          path: ./dist
          retention-days: 1 # 设置保留时间，优化存储

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4 # 更新到 v4 版本
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
